### ISSUE TITLE
My stupid question about Content

### ISSUE THREAD

**Issue by mrranger** [JediKnightChan/EternalCrusadeResurrection#43]
I didn’t understand this text a little, that is, no one can access the Content, or is there just something that needs to be done to get it?

Notice that this project is only the code base, while Content folder is not available for public distribution.

**Comment by JediKnightChan** [comment]
Our Content folder contains various assets that shouldn't be on GitHub publicly, like paid plugins from the marketplace, so yeah,  "no one can access the Content"
